<?php
// Enable error reporting for debugging
error_reporting(E_ALL);
ini_set('display_errors', 1);

$pageTitle = 'Dashboard - SGRC';

// Load dependencies directly
require_once __DIR__ . '/../../config/database.php';

if (session_status() === PHP_SESSION_NONE) {
    session_start();
    }

    // Auth check inline
    if (!isset($_SESSION['user_id'])) {
        header('Location: /SGRC/modules/auth/login.php');
            exit;
            }

            // Load language
            $langFile = __DIR__ . '/../../lang/' . ($_SESSION['lang'] ?? 'fr') . '.php';
            if (file_exists($langFile)) {
                require_once $langFile;
                } else {
                    $lang = [];
                    }

                    $db = Database::getInstance();

                    $stats = [
                        'citizens' => $db->query("SELECT COUNT(*) as c FROM citizens")->fetch()['c'],
                            'registers' => $db->query("SELECT COUNT(*) as c FROM registers")->fetch()['c'],
                                'certificates' => $db->query("SELECT COUNT(*) as c FROM certificates")->fetch()['c'],
                                    'documents' => $db->query("SELECT COUNT(*) as c FROM documents")->fetch()['c'],
                                        'users' => $db->query("SELECT COUNT(*) as c FROM users")->fetch()['c'],
                                            'recent_registers' => $db->query("SELECT r.*, c.first_name, c.last_name FROM registers r LEFT JOIN citizens c ON r.citizen_id = c.id ORDER BY r.created_at DESC LIMIT 5")->fetchAll()
                                            ];

                                            // Include header AFTER all processing
                                            require_once __DIR__ . '/../../includes/header.php';
                                            ?>

                                            <div class="container-fluid">
                                                <h1 class="mb-4"><?php echo $lang['dashboard'] ?? 'Dashboard'; ?></h1>
                                                    
                                                        <div class="row g-4 mb-4">
                                                                <div class="col-md-3">
                                                                            <div class="card bg-primary text-white">
                                                                                            <div class="card-body">
                                                                                                                <h4><?php echo $stats['citizens']; ?></h4>
                                                                                                                                    <p class="mb-0"><?php echo $lang['citizens'] ?? 'Citizens'; ?></p>
                                                                                                                                                    </div>
                                                                                                                                                                </div>
                                                                                                                                                                        </div>
                                                                                                                                                                                <div class="col-md-3">
                                                                                                                                                                                            <div class="card bg-success text-white">
                                                                                                                                                                                                            <div class="card-body">
                                                                                                                                                                                                                                <h4><?php echo $stats['registers']; ?></h4>
                                                                                                                                                                                                                                                    <p class="mb-0"><?php echo $lang['registers'] ?? 'Registers'; ?></p>
                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                <div class="col-md-3">
                                                                                                                                                                                                                                                                                                            <div class="card bg-info text-white">
                                                                                                                                                                                                                                                                                                                            <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                <h4><?php echo $stats['certificates']; ?></h4>
                                                                                                                                                                                                                                                                                                                                                                    <p class="mb-0"><?php echo $lang['certificates'] ?? 'Certificates'; ?></p>
                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                <div class="col-md-3">
                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="card bg-warning text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h4><?php echo $stats['documents']; ?></h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p class="mb-0"><?php echo $lang['documents'] ?? 'Documents'; ?></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="card-header">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h5>Recent Registrations</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <table class="table table-striped">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <th>Register #</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th>Type</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <th>Citizen</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th>Date</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <th>Status</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php foreach ($stats['recent_registers'] as $reg): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td><?php echo htmlspecialchars($reg['register_number']); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td><?php echo $lang[$reg['register_type']] ?? $reg['register_type']; ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td><?php echo htmlspecialchars($reg['first_name'] . ' ' . $reg['last_name']); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td><?php echo $reg['event_date']; ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td><span class="badge bg-<?php echo $reg['status'] === 'active' ? 'success' : 'secondary'; ?>"><?php echo $reg['status']; ?></span></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php endforeach; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php if (empty($stats['recent_registers'])): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <tr><td colspan="5" class="text-center">No recent registrations</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php require_once __DIR__ . '/../../includes/footer.php'; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                