<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
    }

    if (isset($_SESSION['user_id'])) {
        header('Location: /SGRC/modules/dashboard/index.php');
            exit;
            }

            $pageTitle = 'Login - SGRC';
            $error = '';

            if ($_SERVER['REQUEST_METHOD'] === 'POST') {
                require_once __DIR__ . '/../../config/database.php';
                    
                        $username = $_POST['username'] ?? '';
                            $password = $_POST['password'] ?? '';
                                
                                    $db = Database::getInstance();
                                        $user = $db->query("SELECT * FROM users WHERE username = ? AND is_active = 1", [$username])->fetch();
                                            
                                                if ($user && password_verify($password, $user['password_hash'])) {
                                                        $_SESSION['user_id'] = $user['id'];
                                                                $_SESSION['username'] = $user['username'];
                                                                        $_SESSION['user_role'] = $user['role'];
                                                                                $_SESSION['lang'] = 'fr';
                                                                                        $_SESSION['last_activity'] = time();
                                                                                                
                                                                                                        header('Location: /SGRC/modules/dashboard/index.php');
                                                                                                                exit;
                                                                                                                    } else {
                                                                                                                            $error = 'Invalid credentials';
                                                                                                                                }
                                                                                                                                }
                                                                                                                                ?>
                                                                                                                                <!DOCTYPE html>
                                                                                                                                <html lang="fr">
                                                                                                                                <head>
                                                                                                                                    <meta charset="UTF-8">
                                                                                                                                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                                                                                                                            <title><?php echo $pageTitle; ?></title>
                                                                                                                                                <!-- Google Fonts -->
                                                                                                                                                    <link rel="preconnect" href="https://fonts.googleapis.com">
                                                                                                                                                        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
                                                                                                                                                            <!-- Bootstrap -->
                                                                                                                                                                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
                                                                                                                                                                    <!-- Shared Custom CSS -->
                                                                                                                                                                        <link rel="stylesheet" href="/SGRC/assets/css/custom.css">
                                                                                                                                                                            <!-- Font Awesome for icons -->
                                                                                                                                                                                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
                                                                                                                                                                                </head>
                                                                                                                                                                                <body class="login-page">
                                                                                                                                                                                    <div class="login-card">
                                                                                                                                                                                            <div class="login-logo">
                                                                                                                                                                                                        <h2><i class="fas fa-shield-alt me-2"></i>SGRC</h2>
                                                                                                                                                                                                                    <p>Civil Registry Management System</p>
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                            <?php if ($error): ?>
                                                                                                                                                                                                                                                        <div class="alert alert-danger d-flex align-items-center">
                                                                                                                                                                                                                                                                        <i class="fas fa-exclamation-circle me-2"></i>
                                                                                                                                                                                                                                                                                        <?php echo $error; ?>
                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                            <?php endif; ?>
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                            <form method="POST" class="login-form">
                                                                                                                                                                                                                                                                                                                                        <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                        <label class="form-label fw-semibold">Username</label>
                                                                                                                                                                                                                                                                                                                                                                        <div class="input-group">
                                                                                                                                                                                                                                                                                                                                                                                            <span class="input-group-text bg-light border-end-0">
                                                                                                                                                                                                                                                                                                                                                                                                                    <i class="fas fa-user text-muted"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input type="text" name="username" class="form-control border-start-0" placeholder="Enter your username" required autofocus>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label class="form-label fw-semibold">Password</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="input-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span class="input-group-text bg-light border-end-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <i class="fas fa-lock text-muted"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="password" name="password" class="form-control border-start-0" placeholder="Enter your password" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" class="btn btn-primary w-100 mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <i class="fas fa-sign-in-alt me-2"></i>Login
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="forgot_password.php" class="text-decoration-none text-muted small">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <i class="fas fa-key me-1"></i>Forgot password?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        